# Site settings
title: Jiaming Shen's Homepage
email: mickeysjm@gmail.com
# description: Keep it Simple
description: So we beat on, boats against the current, borne back ceaselessly into the past.
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  mickeystroller

# Build settings
markdown: kramdown
